name: 'dbt_weather'
version: '1.0.0'
config-version: 2
profile: 'dbt_weather'
model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  dbt_weather:
    staging:
      +materialized: view
    marts:
      +materialized: table
